### ISSUE TITLE
icarus主题文章优化

### ISSUE THREAD

**Issue by Didudia** [AlphaLxy/AlphaLxy.github.io#2]
作者您好，最近在看您的博客，《icarus文章自定义》中的“优化文章结尾布局”，参考并修改代码的过程中，我发现“readmore”和“tag”的位置跟您的不一样：“readmore”出现在了“tag”下面，请问应该修改什么
![sd](https://user-images.githubusercontent.com/44456221/112570487-17d78f80-8e21-11eb-85ac-e46f8a07ce43.png)

**Comment by AlphaLxy** [comment]
看下 “1.3 优化文章结尾布局”
外面需要包一层`div` `level` + `is-flex`

```html
<div className="level is-mobile is-flex">
```
```css
.level {
    align-items: center;
    justify-content: space-between;
}
```

因此会向两边分布
